name: Prewarm Auction API Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes to keep the server warm

jobs:
  prewarm_server:
    runs-on: ubuntu-latest
    steps:
      - name: Prewarm Auction API
        run: |
          # Make a request to the API endpoint or directly hit the database
          curl -X GET "https://auction-realtime.onrender.com/"
